### PR TITLE
etag: only use normalized_path for remote storage

### PR DESCRIPTION
**Pull request by antonagestam**
fix regression
https://github.com/antonagestam/collectfast/pull/87#discussion_r94890145

### CODE REVIEW

**Comment by antonagestam** [comment]
@AGASS007 Would you mind reviewing this?

**Comment by AGASS007** [comment]
tried it, analyzed it, loved it. thanks man!

**Comment by antonagestam** [comment]
Awesome, thanks again for the feedback! 🍰

**Comment by AGASS007** [comment]
sure thing

**Pull request merged**
