### PR TITLE
Hash gzipped files if AWS_IS_GZIPPED is True

### LINKED ISSUE #46: Doesn't work for gzipped items
If AWS_IS_GZIPPED is set to True, then this will check the hash of the un-gzipped item against the etag of the gzipped item, which will obviously not match (though once upon a time it used to, but amazon fixed that).

This means all js and css files on a set-up using gzipping will be copied on every collect.

### PR DESCRIPTION
**Pull request by rehandalal**
Fixes #46.

~This is a WIP but submitting for feedback.~

### CODE REVIEW

**Comment by rehandalal** [comment]
Filed a PR in django-storages to fix the mtime in `S3Boto3Storage` which should make this work as expected.

**Comment by rehandalal** [comment]
This should be ready for review.

**Comment by rehandalal** [comment]
@antonagestam any chance you could review this? I would love to get this in my project as things are really slow without it. thanks!

**Comment by antonagestam** [comment]
Sorry, I'm not going to review any pull requests on this project until I get an indication from the roadies what their thoughts are on this https://github.com/jazzband/roadies/issues/72
There's a few issues that needs to be sorted.

**Comment by rehandalal** [comment]
@antonagestam I 100% agree with you on having a process around contribution. It kind of sucks to have people committing code, free from any review, to master. That being said, I hope you'd be willing to reconsider not reviewing PRs as I feel like that only bolsters the notion that having a process like review of pull requests is tedious and holds up development.

**Comment by mbeacom** [comment]
I apologize for requesting your review. I requested your review of the PR since it's your repository and you were involved with the original issue. Hopefully I didn't step on any toes.  A process with guidelines would be ideal. In any case, I hope you get everything sorted out!

**Comment by antonagestam** [comment]
@rehandalal How is the performance of this looking in your tests? Also, is the gzipping deterministic so that it generates the same zipped content locally as it will for amazon remotely?

**Comment by antonagestam** [comment]
This is now published in the 0.6.0 release. Thank you again for the contribution!

**Comment by rehandalal** [comment]
Thanks for publishing this. 

To answer your questions:
- Yes, the gzipping is deterministic.
- On first run it appears to have little to no benefit, however subsequent runs are much faster as long as the cache has not expired.

**Pull request closed without merging**
