### PR TITLE
Collectfast 2.0

### PR DESCRIPTION
**Pull request by antonagestam**
- Drop support for Python 3.5
- Drop support for Django 1.11
- Drop support for `storages.backends.s3boto.S3BotoStorage` (`collectfast.strategies.boto.BotoStrategy`)
- Drop support for guessing strategies, e.g. require `COLLECTFAST_STRATEGY` to be set
- Replace comment syntax with type annotation syntax
- Migrate to setup.cfg 
- Start packaging typing information

### Todo

- ~~Stop special-casing Python 3.8 in travis conf~~ #169 
- ~~Consolidate test-requirements and lint-requirements~~ #170

### CODE REVIEW

**Comment by browniebroke** [comment]
Question: is the latest release `1.3.1` already supporting Django 3.0? I see 3.0 has been added to the CI on master, but there are other changes and it's not clear if any fix was specifically done for adding support.

Are you planning to release a 1.4.0 before doing 2.0 and dropping support for 1.11? 

Thanks for your work in maintaining this 😄 

(Background: this is for https://github.com/pydanny/cookiecutter-django/issues/2352)

**Comment by antonagestam** [comment]
@browniebroke Great question, I'd have to dig a bit to refresh my memory. I don't have anything against releasing a fix release with current trunk just to make the support explicit (that would be 1.3.2).

I am not planning a 1.4.0 release, and I will most likely wait until 1.11 is EOL before releasing 2.0. I have generally tried to make the latest release support whatever versions Django are supporting themselves, e.g. following this schedule: https://www.djangoproject.com/download/

**Comment by antonagestam** [comment]
(If I recall correctly there were no changes made for Django 3.0)

**Comment by browniebroke** [comment]
Ok thanks. I don't mind too much if it's 1.3.2 or 1.4.0 to be honest, whatever you feel appropriate is good with me 👍 

If it's not too much effort, a new release would be nice, yes. It would bring us one step closer from upgrading the cookiecutter template on our end.

Anyway, thanks for getting back to me so quickly!

**Comment by antonagestam** [comment]
@browniebroke Hmm, yes kind of a philosophical question if one should bump minor or not here I guess. 🤷‍♂️ The sets of features would be identical, unless the *support* for Django 3.0 itself should be considered a feature, and perhaps there's some value in doing that. Anyway, I'll try to find the time for this as soon as I can.

**Comment by antonagestam** [comment]
@browniebroke After a few issues with backwards incompatible changes in django-storages breaking the build, [1.3.2](https://github.com/antonagestam/collectfast/releases/tag/1.3.2) is now released on PyPI.

**Pull request merged**
