### PR TITLE
Compatibility with Django 1.8

### PR DESCRIPTION
**Pull request by aericson**

### CODE REVIEW

**Comment by aericson** [comment]
Any ideas what could have caused the coveralls multiple comments? There was an update to the pull request after the first 6 comments.

**Comment by antonagestam** [comment]
@aericson Yeah, I think tests are running on both TravisCI and CircleCI, sorry about that.

**Comment by aericson** [comment]
No worries was just wondering since I changed the .travis.yml. Let me know if you need any changes to the PR

**Comment by antonagestam** [comment]
Absolutely, will take a closer look some day soon, but it looks good! :+1:

**Pull request merged**
